version: "3"

services:
  app:
    build: ./
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - DATABSE_HOST=db
      - REDIS_HOST=redis
      - DATABASE_PASSWORD=securedbpassword
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=securedbpassword
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  postgres_data:
  redis_data:
